site_name: FoundryVTT - Shadowrun 6

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top

extra:
  tags:
    interface: interface
    fiche: fiche
    sheet: sheet

plugins:
  - tags:
      enabled: true
      tags_file: tags.md

markdown_extensions:
  - pymdownx.keys

nav:
  - English Documentation:
    - en/index.md
    - System:
      - Entities:
        - Actor Entity: en/entities/actors/index.md
        - Item Entity: en/entities/items/index.md
    - User Interface:
      - en/interface/index.md
      - Sheets:
        - Actors Sheets:
          - Character Sheet: en/interface/sheets/actors/character.md
          - Grunt Sheet: en/interface/sheets/actors/grunt.md
        - Items Sheets:
          - Device Sheet: en/interface/sheets/items/device.md

  - Documentation Française:
    - fr/index.md
    - Système:
      - Entités:
        - Entité Acteur: fr/entites/acteurs/index.md
        - Entité Objet: fr/entites/objets/index.md
    - Interface Utilisateur:
      - en/interface/index.md
      - Fiches:
        - Fiches d'Acteurs:
          - Fiche de Personnage: fr/interface/fiches/acteurs/personnage.md
          - Fiche de Brute: fr/interface/fiches/acteurs/brute.md
        - Fiches d'Objets:
          - Fiche d'Appareil: fr/interface/fiches/objets/appareil.md

  - Tags:
    - tags.md